[package]
name          = "dangod"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }

[[bin]]
name = "dangod"
path = "src/main.rs"

[dependencies]
anyhow             = { workspace = true }
bip32              = { workspace = true }
clap               = { workspace = true, features = ["derive", "wrap_help"] }
colored            = { workspace = true }
colored_json       = { workspace = true }
dango-genesis      = { workspace = true }
dango-types        = { workspace = true }
dialoguer          = { workspace = true }
grug               = { workspace = true }
grug-client        = { workspace = true }
hex                = { workspace = true }
home               = { workspace = true }
k256               = { workspace = true }
rand               = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
tendermint-rpc     = { workspace = true, features = ["http-client"] }
tokio              = { workspace = true }
toml               = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
